owner: sknkwoxs
repo: upptime
# https://github.com/upptime/upptime/issues/625
delay: 2000
skipDeleteIssues: true
sites:
  - name: 국경없는의사회 msf
    url: https://msf.or.kr
  - name: 서울정책아카이브 seoulsolution
    url: https://seoulsolution.kr
    __dangerous__insecure: true
  - name: 전문무용수지원센터 dcdcenter
    url: https://dcdcenter.or.kr
  - name: 패밀리서울 familyseoul
    url: https://familyseoul.or.kr
  - name: APCEIU CDI
    url: https://gcedcurriculum.org
  - name: APCEIU ClearingHouse
    url: https://gcedclearinghouse.org
  - name: KACE
    url: https://ukace.or.kr
  - name: OTW-WEB
    url: https://oxfamtrailwalker.or.kr
    __dangerous__insecure: true
  - name: RNjob WEB
    url: https://rnjob.or.kr
  - name: YWCA
    url: https://ywca.or.kr
  - name: 마일스톤 mstacc
    url: https://mstacc.com
  #- name: 노을 noul
  #  url: https://noul.com
  - name: 삼화페인트 samhwa
    url: https://samhwa.com
  - name: 위스타트 westart
    url: https://westart.or.kr
  - name: 이지스 블로그 igis-blog
    url: https://blog.igisam.com
  - name: 한울타리 mcfamily
    url: https://mcfamily.or.kr
  - name: 프론트원 front1
    url: https://front1.kr
  - name: 디캠프 dcamp
    url: https://dcamp.kr
  - name: 공공결혼식 wedding
    url: https://wedding.seoulwomen.or.kr
  - name: 간호실무 nursingnavi
    url: https://nursingnavi.rnjob.or.kr
  - name: 한국사회가치연대기금 svsfund
    url: https://svsfund.org/
  - name: 사회적금융허브 socialfinance
    url: https://socialfinance.kr/
  - name: 서울시어르신돌봄종사자종합지원센터 dolbom
    url: https://www.dolbom.org/

status-website:
  cname: status.skunkworks.co.kr
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
