owner: sknkwoxs
repo: upptime
# https://github.com/upptime/upptime/issues/625
delay: 2000
skipDeleteIssues: true
sites:
  - name: 국경없는 의사회 msf
    url: https://msf.or.kr
  - name: 서울정책아카이브 seoulsolution
    url: https://seoulsolution.kr
    __dangerous__insecure: true
  - name: 전문무용수지원센터 dcdcenter
    url: https://dcdcenter.or.kr
  - name: 패밀리서울 familyseoul
    url: https://familyseoul.or.kr
  - name: APCEIU CDI
    url: https://gcedcurriculum.org
  - name: KACE
    url: https://ukace.or.kr
  - name: OTW-WEB
    url: https://oxfamtrailwalker.or.kr
    __dangerous__insecure: true
  - name: OTW-WEB(v50)
    url: https://v50.oxfamtrailwalker.or.kr
  - name: RNjob WEB
    url: https://rnjob.or.kr
  - name: 사경포털 sehub
    url: https://sehub.net
  - name: YWCA
    url: https://ywca.or.kr
  - name: 마일스톤 mstacc
    url: https://mstacc.com
  - name: 노을 noul
    url: https://noul.kr
  - name: 삼화페인트 samhwa
    url: https://samhwa.com
  - name: 위스타트 westart
    url: https://westart.or.kr
  - name: 이지스 블로그 igis-blog
    url: https://blog.igisam.com
  - name: 아트브릿지 artbridge
    url: http://artbridge.or.kr
  - name: OXFAM KOREA
    url: https://oxfam.or.kr
  - name: 한울타리 mcfamily
    url: https://mcfamily.or.kr
  - name: 프론트원 front1
    url: https://front1.kr
  - name: GSEF
    url: https://gsef-net.org
  - name: 디캠프 dcamp
    url: https://dcamp.kr

status-website:
  cname: status.skunkworks.co.kr
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
