owner: sknkwoxs
repo: upptime

sites:
  - name: 국경없는 의사회
    url: https://msf.or.kr
  - name: 서울정책아카이브
    url: https://seoulsolution.kr
  - name: 전문무용수지원센터
    url: https://dcdcenter.or.kr
  - name: 패밀리서울
    url: https://familyseoul.or.kr
  - name: APCEIU CDI
    url: https://gcedcurriculum.org
  - name: KACE
    url: https://ukace.or.kr
  - name: OTW-WEB
    url: https://oxfamtrailwalker.or.kr
  - name: OTW-WEB(v50)
    url: https://v50.oxfamtrailwalker.or.kr
  - name: RNjob WEB
    url: https://rnjob.or.kr
  - name: 사경포털
    url: https://sehub.net
  - name: YWCA
    url: https://ywca.or.kr
  - name: 마일스톤
    url: https://mstacc.com
  - name: 노을
    url: https://noul.kr
  - name: 삼화페인트
    url: https://samhwa.com
  - name: 위스타트
    url: https://westart.or.kr
  - name: 이지스 블로그
    url: https://blog.igisam.com
  - name: 아트브릿지
    url: https://artbridge.or.kr
  - name: OXFAM KOREA
    url: https://oxfam.or.kr
  - name: 한울타리
    url: https://mcfamily.or.kr
  - name: 서울정책아카이브
    url: https://seoulsolution.kr
  - name: 위스타트
    url: https://westart.or.kr
  - name: 프론트원
    url: https://front1.kr
  - name: 사경포털
    url: https://sehub.net
  - name: GSEF
    url: https://gsef-net.org

status-website:
  cname: status.skunkworks.co.kr
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
